"""Gatekeeper — integration and compilation engine for The Forge."""

from __future__ import annotations

import json
import os
import re
import shutil
import subprocess
import sys
from dataclasses import dataclass
from pathlib import Path

try:
    from gatekeeper.models import GatekeeperResult, RoslynError
except ImportError:
    from models import GatekeeperResult, RoslynError

try:
    from forge_master.compilation_harness import find_tmod_path
except ImportError:
    _fm_path = str(Path(__file__).resolve().parent.parent / "forge_master")
    if _fm_path not in sys.path:
        sys.path.insert(0, _fm_path)
    from compilation_harness import find_tmod_path

# Regex: filename(line,col): error CSxxxx: message
_ERROR_RE = re.compile(
    r"^(?P<file>[^\s(]+)\((?P<line>\d+),\d+\):\s+error\s+(?P<code>CS\d{4}):\s+(?P<message>.+)$",
    re.MULTILINE,
)

# Regex: class FooBar : ModItem
_ITEM_NAME_RE = re.compile(r"class\s+(\w+)\s*:\s*ModItem\b")


_DEFAULT_BUILD_TXT = """\
displayName = ForgeGeneratedMod
author = The Forge
version = 0.1
"""

_DEFAULT_DESCRIPTION_TXT = "A mod generated by The Forge.\n"

_MAX_RETRIES = 3

_DEFAULT_MOD_SOURCE_PATH = (
    Path.home() / "Library" / "Application Support" / "Terraria"
    / "tModLoader" / "ModSources" / "ForgeGeneratedMod"
)


@dataclass
class CompileResult:
    """Result of a tModLoader build attempt."""
    success: bool
    output: str  # combined stdout + stderr


class Integrator:
    """Stages mod files, runs tModLoader builds, and self-heals via LLM repair."""

    def __init__(self, coder=None) -> None:
        mod_source = os.environ.get("MOD_SOURCE_PATH")
        self._mod_root = Path(mod_source) if mod_source else _DEFAULT_MOD_SOURCE_PATH

        tmod_path = find_tmod_path()
        self._tmod_dll = (tmod_path / "tModLoader.dll") if tmod_path else None

        self._coder = coder
        self._max_retries = _MAX_RETRIES

    def build_and_verify(self, forge_output: dict, sprite_path: str | None = None, projectile_sprite_path: str | None = None) -> dict:
        """Main entry point. Stage files, build, self-heal, return result."""
        if forge_output.get("status") == "error":
            return GatekeeperResult(
                status="error",
                item_name="",
                attempts=0,
                error_message="Received error output from CoderAgent.",
            ).model_dump()

        cs_code = forge_output["cs_code"]
        hjson_code = forge_output.get("hjson_code", "")
        item_name = self._extract_item_name(cs_code)

        if not item_name:
            return GatekeeperResult(
                status="error",
                item_name="",
                attempts=0,
                error_message="Could not extract ModItem class name from C# source.",
            ).model_dump()

        self._write_status({"status": "building"})
        self._stage_files(cs_code, hjson_code, item_name, sprite_path, projectile_sprite_path)

        for attempt in range(1, self._max_retries + 2):
            result = self._run_tmod_build()

            if result.success:
                self._ensure_mod_enabled("ForgeGeneratedMod")
                self._write_status({
                    "status": "ready",
                    "message": "Compilation successful. Waiting for user...",
                })
                return GatekeeperResult(
                    status="success",
                    item_name=item_name,
                    attempts=attempt,
                ).model_dump()

            errors = self._parse_errors(result.output)

            if attempt > self._max_retries:
                error_code = errors[0].code if errors else "UNKNOWN"
                self._write_status({
                    "status": "error",
                    "error_code": error_code,
                    "message": "Critical Failure: The compiler rejected the generated logic.",
                })
                return GatekeeperResult(
                    status="error",
                    item_name=item_name,
                    attempts=attempt,
                    errors=errors,
                    error_message=f"Build failed after {self._max_retries} retries.",
                ).model_dump()

            if not self._coder:
                try:
                    from forge_master.forge_master import CoderAgent
                except ImportError:
                    from forge_master import CoderAgent
                self._coder = CoderAgent()

            repair_result = self._coder.fix_code(
                error_log=result.output,
                original_code=cs_code,
            )

            if repair_result.get("status") == "error":
                error_code = errors[0].code if errors else "UNKNOWN"
                self._write_status({
                    "status": "error",
                    "error_code": error_code,
                    "message": "Critical Failure: The compiler rejected the generated logic.",
                })
                return GatekeeperResult(
                    status="error",
                    item_name=item_name,
                    attempts=attempt + 1,
                    errors=errors,
                    error_message="CoderAgent repair failed.",
                ).model_dump()

            cs_code = repair_result["cs_code"]
            self._stage_files(cs_code, hjson_code, item_name, sprite_path=None, projectile_sprite_path=None)

    @staticmethod
    def _parse_errors(output: str) -> list[RoslynError]:
        """Extract structured Roslyn errors from dotnet build output."""
        errors = []
        for m in _ERROR_RE.finditer(output):
            errors.append(RoslynError(
                code=m.group("code"),
                message=m.group("message"),
                line=int(m.group("line")),
                file=m.group("file"),
            ))
        return errors

    @staticmethod
    def _extract_item_name(cs_code: str) -> str | None:
        """Extract the ModItem class name from C# source."""
        m = _ITEM_NAME_RE.search(cs_code)
        return m.group(1) if m else None

    def _write_status(self, status_dict: dict) -> None:
        """Write generation_status.json to the mod root directory."""
        self._mod_root.mkdir(parents=True, exist_ok=True)
        status_path = self._mod_root / "generation_status.json"
        status_path.write_text(
            json.dumps(status_dict, indent=2) + "\n", encoding="utf-8"
        )

    def _stage_files(
        self,
        cs_code: str,
        hjson_code: str,
        item_name: str,
        sprite_path: str | None,
        projectile_sprite_path: str | None = None,
    ) -> None:
        """Write CS and PNG to Content/Items/."""
        items_dir = self._mod_root / "Content" / "Items"
        items_dir.mkdir(parents=True, exist_ok=True)

        (items_dir / f"{item_name}.cs").write_text(cs_code, encoding="utf-8")

        if sprite_path and Path(sprite_path).exists():
            shutil.copy2(sprite_path, items_dir / f"{item_name}.png")

        if projectile_sprite_path and Path(projectile_sprite_path).exists():
            shutil.copy2(projectile_sprite_path, items_dir / Path(projectile_sprite_path).name)

        if hjson_code:
            self._merge_hjson(hjson_code, item_name)

        self._ensure_build_files()

    def _ensure_build_files(self) -> None:
        """Create build.txt and description.txt if they don't exist."""
        build_txt = self._mod_root / "build.txt"
        desc_txt = self._mod_root / "description.txt"
        if not build_txt.exists():
            build_txt.write_text(_DEFAULT_BUILD_TXT, encoding="utf-8")
        if not desc_txt.exists():
            desc_txt.write_text(_DEFAULT_DESCRIPTION_TXT, encoding="utf-8")

    def _merge_hjson(self, hjson_block: str, item_name: str) -> None:
        """Append or replace an item's HJSON block in en-US.hjson."""
        hjson_path = self._mod_root / "Localization" / "en-US.hjson"
        hjson_path.parent.mkdir(parents=True, exist_ok=True)

        if not hjson_path.exists():
            hjson_path.write_text(hjson_block, encoding="utf-8")
            return

        existing = hjson_path.read_text(encoding="utf-8")

        # Extract the new item's inner block (ItemName: { ... })
        new_item_re = re.compile(
            rf"({re.escape(item_name)}:\s*\{{[^{{}}]*\}})", re.DOTALL
        )
        new_match = new_item_re.search(hjson_block)
        if not new_match:
            hjson_path.write_text(hjson_block, encoding="utf-8")
            return

        new_item_block = new_match.group(1)

        # Check if this item already exists
        existing_match = new_item_re.search(existing)
        if existing_match:
            # Replace existing block
            updated = existing[:existing_match.start()] + new_item_block + existing[existing_match.end():]
            hjson_path.write_text(updated, encoding="utf-8")
        else:
            # Insert before the closing of the Items block
            items_close = re.search(r"(\n\t\t\})", existing)
            if items_close:
                insert_pos = items_close.start()
                updated = existing[:insert_pos] + "\n\t\t\t" + new_item_block + existing[insert_pos:]
                hjson_path.write_text(updated, encoding="utf-8")
            else:
                hjson_path.write_text(hjson_block, encoding="utf-8")

    def _ensure_mod_enabled(self, mod_name: str) -> None:
        """Ensure mod_name appears in tModLoader's enabled.json."""
        enabled_path = (
            Path.home() / "Library" / "Application Support" / "Terraria"
            / "tModLoader" / "Mods" / "enabled.json"
        )
        enabled_path.parent.mkdir(parents=True, exist_ok=True)

        try:
            enabled: list[str] = json.loads(enabled_path.read_text(encoding="utf-8")) if enabled_path.exists() else []
        except (json.JSONDecodeError, OSError):
            enabled = []

        if mod_name not in enabled:
            enabled.append(mod_name)
            tmp = enabled_path.with_suffix(".tmp")
            tmp.write_text(json.dumps(enabled, indent=2) + "\n", encoding="utf-8")
            tmp.replace(enabled_path)

    def _run_tmod_build(self) -> CompileResult:
        """Run the tModLoader headless build as a blocking subprocess.

        macOS SIP strips DYLD_* env vars from child processes, so we use a
        wrapper shell script that sets DYLD_LIBRARY_PATH and ``exec``s dotnet
        in-place — preserving the variable for native library resolution.
        """
        mod_name = self._mod_root.name
        mod_sources_dir = self._mod_root.parent
        tmod_dir = self._tmod_dll.parent
        saved_dir = mod_sources_dir.parent  # e.g. .../tModLoader

        wrapper = Path(__file__).resolve().parent / "tmod_build.sh"

        cmd = [
            str(wrapper),
            str(tmod_dir),
            "-build",
            mod_name,
            "-tmlsavedirectory",
            str(saved_dir),
        ]

        proc = subprocess.run(
            cmd,
            capture_output=True,
            text=True,
        )
        output = proc.stdout + proc.stderr
        return CompileResult(success=proc.returncode == 0, output=output)
