"""Gatekeeper — integration and compilation engine for The Forge."""

from __future__ import annotations

import json
import os
import re
import shutil
import subprocess
import sys
from dataclasses import dataclass
from pathlib import Path

try:
    from gatekeeper.models import GatekeeperResult, RoslynError
except ImportError:
    from models import GatekeeperResult, RoslynError

try:
    from core.atomic_io import atomic_write_text as _atomic_write_text
    from core.paths import mod_sources_root
except ImportError:
    import sys as _sys

    _parent = str(Path(__file__).resolve().parent.parent)
    if _parent not in _sys.path:
        _sys.path.insert(0, _parent)
    from core.atomic_io import atomic_write_text as _atomic_write_text
    from core.paths import mod_sources_root

try:
    from core.compilation_harness import find_tmod_path
except ImportError:
    from compilation_harness import find_tmod_path  # type: ignore

# Regex: filename(line,col): error CSxxxx: message
_ERROR_RE = re.compile(
    r"^(?P<file>[^\s(]+)\((?P<line>\d+),\d+\):\s+error\s+(?P<code>CS\d{4}):\s+(?P<message>.+)$",
    re.MULTILINE,
)

# tModLoader packaging step (after Roslyn) — e.g. TML003 when .tmod is locked by the game
_TML_ERROR_RE = re.compile(
    r"tModLoader:\s*Mod Build error\s+(?P<code>TML\d+):\s*(?P<message>.+)$",
    re.MULTILINE | re.IGNORECASE,
)


def _is_real_tml_error(code: str) -> bool:
    """True for tModLoader-reported errors (TML###), False for the synthetic TML_LOCK sentinel."""
    return code.startswith("TML") and code != "TML_LOCK"


# When the numbered TML line is missing but packaging still failed (locked .tmod).
_TMOD_FILE_LOCK_RE = re.compile(
    r"cannot access the file\s+['\"](?P<path>[^'\"]+\.tmod)['\"].*another process",
    re.IGNORECASE | re.DOTALL,
)

# TML003 / IOException on .tmod — same situation as the official modding wiki (external build
# while the client holds the packaged file). See:
# https://github.com/tModLoader/tModLoader/wiki/Developing-with-Visual-Studio-Code#common-build-issues
_MSG_TML003 = (
    "Packaging failed (TML003): the .tmod file is in use. Disable ForgeGeneratedMod in "
    "tModLoader and reload mods, or close tModLoader completely, then build again."
)

# Regexes: class FooBar : ModItem / ModProjectile. Generated code usually imports
# Terraria.ModLoader, but tests and repairs can use fully qualified base names.
_ITEM_NAME_RE = re.compile(
    r"class\s+(\w+)\s*:\s*(?:[\w.]+\.)?ModItem\b"
)
_PROJECTILE_NAME_RE = re.compile(
    r"class\s+(\w+)\s*:\s*(?:[\w.]+\.)?ModProjectile\b"
)
_VANILLA_TEXTURE_RE = re.compile(
    r"override\s+string\s+Texture\b[\s\S]*?\"Terraria/Images/"
)


_DEFAULT_BUILD_TXT = """\
displayName = ForgeGeneratedMod
author = The Forge
version = 0.1
"""

_DEFAULT_DESCRIPTION_TXT = "A mod generated by The Forge.\n"

# tModLoader requires a Mod subclass whose namespace matches the mod folder name
# (AssemblyManager.VerifyMod). LLM output often only adds Content/Items/*.cs — supply the entry.
_DEFAULT_MOD_ENTRY_CS = """using Terraria.ModLoader;

namespace {mod_name}
{{
    public class {mod_name} : Mod
    {{
    }}
}}
"""

_MAX_RETRIES = 3


def _atomic_write_json(path: Path, obj: dict) -> None:
    """Atomically write JSON via :func:`_atomic_write_text`."""
    _atomic_write_text(path, json.dumps(obj, indent=2) + "\n")


def default_mod_sources_dir() -> Path:
    """tModLoader ModSources root (aligned with orchestrator / TUI — see agents/paths.py)."""
    return mod_sources_root()


def tmod_enabled_json_path() -> Path:
    """tModLoader ``Mods/enabled.json`` next to ModSources."""
    return default_mod_sources_dir().parent / "Mods" / "enabled.json"


def _hjson_block_end(s: str, open_brace_idx: int) -> int | None:
    """*open_brace_idx* points at ``{``; return index one past the matching
    ``}``, respecting double-quoted strings so ``}`` inside tooltips is ignored.
    """
    if open_brace_idx < 0 or open_brace_idx >= len(s) or s[open_brace_idx] != "{":
        return None
    depth = 0
    i = open_brace_idx
    in_str = False
    esc = False
    while i < len(s):
        c = s[i]
        if in_str:
            if esc:
                esc = False
            elif c == "\\":
                esc = True
            elif c == '"':
                in_str = False
        else:
            if c == '"':
                in_str = True
            elif c == "{":
                depth += 1
            elif c == "}":
                depth -= 1
                if depth == 0:
                    return i + 1
        i += 1
    return None


def _extract_item_hjson_block(text: str, item_name: str) -> str | None:
    """Return the substring ``Name: { ... }`` for one mod item, or *None*."""
    head = re.search(rf"({re.escape(item_name)}:\s*{{)", text)
    if not head:
        return None
    open_idx = head.end() - 1
    end = _hjson_block_end(text, open_idx)
    if end is None:
        return None
    return text[head.start() : end]


@dataclass
class CompileResult:
    """Result of a tModLoader build attempt."""

    success: bool
    output: str  # combined stdout + stderr


class Integrator:
    """Stages mod files, runs tModLoader builds, and self-heals via LLM repair."""

    def __init__(self, coder=None) -> None:
        mod_source = os.environ.get("MOD_SOURCE_PATH")
        if mod_source:
            mod_root = Path(mod_source).expanduser()
            if mod_root.parent.name != "ModSources":
                mod_root = mod_root.parent / "ModSources" / mod_root.name
            self._mod_root = mod_root
        else:
            self._mod_root = default_mod_sources_dir() / "ForgeGeneratedMod"

        tmod_path = find_tmod_path()
        self._tmod_dll = (tmod_path / "tModLoader.dll") if tmod_path else None

        self._coder = coder
        self._max_retries = _MAX_RETRIES

    def build_and_verify(
        self,
        forge_output: dict,
        sprite_path: str | None = None,
        projectile_sprite_path: str | None = None,
        manifest: dict | None = None,
    ) -> dict:
        """Main entry point. Stage files, build, self-heal, return result."""
        if forge_output.get("status") == "error":
            return GatekeeperResult(
                status="error",
                item_name="",
                attempts=0,
                error_message="Received error output from CoderAgent.",
            ).model_dump()

        cs_code = forge_output["cs_code"]
        hjson_code = forge_output.get("hjson_code", "")
        item_name = self._extract_item_name(cs_code)

        if not item_name:
            return GatekeeperResult(
                status="error",
                item_name="",
                attempts=0,
                error_message="Could not extract ModItem class name from C# source.",
            ).model_dump()

        preflight_errors = self._manifest_contract_errors(manifest, cs_code)
        if preflight_errors:
            message = "Generated code failed manifest contract preflight: " + "; ".join(
                preflight_errors
            )
            self._write_status(
                {
                    "status": "error",
                    "error_code": "MANIFEST_CONTRACT",
                    "message": message,
                }
            )
            return GatekeeperResult(
                status="error",
                item_name=item_name,
                attempts=0,
                error_message=message,
            ).model_dump()

        self._write_status({"status": "building"})
        self._stage_files(
            cs_code,
            hjson_code,
            item_name,
            sprite_path,
            projectile_sprite_path,
            manifest=manifest,
        )

        for attempt in range(1, self._max_retries + 2):
            result = self._run_tmod_build()

            if result.success:
                self._ensure_mod_enabled(self._mod_root.name)
                self._write_status(
                    {
                        "status": "finishing",
                        "message": "Compilation successful. Finalizing...",
                    }
                )
                return GatekeeperResult(
                    status="success",
                    item_name=item_name,
                    attempts=attempt,
                ).model_dump()

            errors = self._parse_errors(result.output)

            if self._is_packaging_only_failure(errors):
                user_msg = self._packaging_failure_summary(errors)
                code = self._first_tml_code(errors)
                self._write_status(
                    {
                        "status": "error",
                        "error_code": code,
                        "message": user_msg,
                    }
                )
                return GatekeeperResult(
                    status="error",
                    item_name=item_name,
                    attempts=attempt,
                    errors=errors,
                    error_message=user_msg,
                ).model_dump()

            if attempt > self._max_retries:
                error_code = errors[0].code if errors else "UNKNOWN"
                self._write_status(
                    {
                        "status": "error",
                        "error_code": error_code,
                        "message": "Critical Failure: The compiler rejected the generated logic.",
                    }
                )
                return GatekeeperResult(
                    status="error",
                    item_name=item_name,
                    attempts=attempt,
                    errors=errors,
                    error_message=f"Build failed after {self._max_retries} retries.",
                ).model_dump()

            error_code = errors[0].code if errors else "UNKNOWN"
            self._write_status(
                {
                    "status": "error",
                    "error_code": error_code,
                    "message": "Critical Failure: The compiler rejected the generated logic.",
                }
            )
            return GatekeeperResult(
                status="error",
                item_name=item_name,
                attempts=attempt,
                errors=errors,
                error_message=f"Build failed on attempt {attempt}.",
            ).model_dump()

        # Should be unreachable, but guard against falling through.
        return GatekeeperResult(
            status="error",
            item_name=item_name,
            attempts=self._max_retries + 1,
            error_message="Build loop exited unexpectedly.",
        ).model_dump()

    @staticmethod
    def _manifest_contract_errors(manifest: dict | None, cs_code: str) -> list[str]:
        if not isinstance(manifest, dict) or not manifest:
            return []
        from core.critique_rules import critique_violations, validate_projectile_hitbox_contract
        return validate_projectile_hitbox_contract(manifest, cs_code) + critique_violations(
            manifest, cs_code
        )

    @staticmethod
    def _parse_errors(output: str) -> list[RoslynError]:
        """Extract Roslyn CS#### errors and tModLoader TML### packaging errors from build output."""
        errors: list[RoslynError] = []
        for m in _ERROR_RE.finditer(output):
            errors.append(
                RoslynError(
                    code=m.group("code"),
                    message=m.group("message"),
                    line=int(m.group("line")),
                    file=m.group("file"),
                )
            )
        for m in _TML_ERROR_RE.finditer(output):
            errors.append(
                RoslynError(
                    code=m.group("code"),
                    message=m.group("message").strip(),
                    line=None,
                    file=None,
                )
            )
        has_cs = any(e.code.startswith("CS") for e in errors)
        has_tml = any(e.code.startswith("TML") for e in errors)
        if not has_cs and not has_tml and _TMOD_FILE_LOCK_RE.search(output):
            errors.append(
                RoslynError(
                    code="TML_LOCK",
                    message=_MSG_TML003,
                    line=None,
                    file=None,
                )
            )
        return errors

    @staticmethod
    def _is_packaging_only_failure(errors: list[RoslynError]) -> bool:
        """True when the build failed for packaging/env reasons, not Roslyn — LLM repair cannot help."""
        if any(e.code.startswith("CS") for e in errors):
            return False
        return any(e.code.startswith("TML") for e in errors)

    @staticmethod
    def _packaging_failure_summary(errors: list[RoslynError]) -> str:
        """User-facing message for TUI / orchestrator."""
        for e in errors:
            if e.code == "TML003":
                return _MSG_TML003
            if _is_real_tml_error(e.code):
                return f"Packaging failed ({e.code}): {e.message}"
        return "Packaging failed: unknown TML error."

    @staticmethod
    def _first_tml_code(errors: list[RoslynError]) -> str:
        """Prefer a concrete TML### from tMod output; map inferred TML_LOCK to TML003 for stable TUI labels."""
        lock_found = False
        for e in errors:
            if _is_real_tml_error(e.code):
                return e.code
            if e.code == "TML_LOCK":
                lock_found = True
        return "TML003" if lock_found else "UNKNOWN"

    @staticmethod
    def _extract_item_name(cs_code: str) -> str | None:
        """Extract the ModItem class name from C# source."""
        m = _ITEM_NAME_RE.search(cs_code)
        return m.group(1) if m else None

    @staticmethod
    def _extract_projectile_name(cs_code: str) -> str | None:
        """Extract the first ModProjectile class name from C# source."""
        m = _PROJECTILE_NAME_RE.search(cs_code)
        return m.group(1) if m else None

    @staticmethod
    def _class_body(cs_code: str, class_name: str) -> str:
        """Return the text inside a class body using balanced braces."""
        match = re.search(rf"class\s+{re.escape(class_name)}\b", cs_code)
        if not match:
            return ""

        open_idx = cs_code.find("{", match.end())
        if open_idx == -1:
            return ""

        depth = 0
        for idx in range(open_idx, len(cs_code)):
            char = cs_code[idx]
            if char == "{":
                depth += 1
                continue
            if char != "}":
                continue
            depth -= 1
            if depth == 0:
                return cs_code[open_idx + 1 : idx]
        return ""

    @classmethod
    def _uses_vanilla_texture(cls, cs_code: str, class_name: str) -> bool:
        """True when a generated class explicitly points Texture at Terraria assets."""
        return bool(_VANILLA_TEXTURE_RE.search(cls._class_body(cs_code, class_name)))

    @staticmethod
    def _resolve_staging_hjson(
        hjson_code: str,
        manifest: dict | None,
        item_name: str,
        mod_folder_name: str,
    ) -> str:
        """Prefer manifest-driven localization so tooltip markup cannot break Hjson.

        Manifest-driven generation JSON-encodes display/tooltip strings, preventing
        hjson corruption from raw newlines or ``}`` inside unquoted Terraria color tags.
        """
        if not isinstance(manifest, dict):
            return hjson_code
        if "display_name" not in manifest and "tooltip" not in manifest:
            return hjson_code
        from core.hjson_gen import generate_hjson
        display = str(manifest.get("display_name", item_name))
        tooltip = str(manifest.get("tooltip", ""))
        return generate_hjson(
            item_name=item_name,
            display_name=display,
            tooltip=tooltip,
            mod_name=mod_folder_name,
        )

    @classmethod
    def _inject_mod_projectile_texture(
        cls,
        cs_code: str,
        projectile_name: str | None,
        mod_name: str,
        use_mod_projectile_png: bool,
    ) -> str:
        """Point ModProjectile at ``Content/Projectiles`` when the .cs file lives in ``Content/Items``.

        tModLoader default texture resolution follows the *source* path; a ModProjectile
        class nested in ``Content/Items/ItemName.cs`` otherwise looks for
        ``.../Content/Items/ProjectileClass`` even when the .png is staged to
        ``Content/Projectiles/ProjectileClass.png``.
        """
        if not projectile_name or not use_mod_projectile_png:
            return cs_code
        if cls._uses_vanilla_texture(cs_code, projectile_name):
            return cs_code

        right = f'"{mod_name}/Content/Projectiles/{projectile_name}"'
        wrong_mod = f'"{mod_name}/Content/Items/{projectile_name}"'
        if wrong_mod in cs_code:
            return cs_code.replace(wrong_mod, right, 1)
        if f'"Content/Items/{projectile_name}"' in cs_code:
            return cs_code.replace(
                f'"Content/Items/{projectile_name}"', right, 1
            )

        body = cls._class_body(cs_code, projectile_name)
        if not body or re.search(r"override\s+string\s+Texture", body):
            return cs_code

        m = re.search(
            rf"public\s+class\s+{re.escape(projectile_name)}\s*:\s*ModProjectile\s*{{",
            cs_code,
            re.DOTALL,
        )
        if not m:
            return cs_code
        insert_at = m.end()
        line = f"\n\tpublic override string Texture => {right};\n"
        return cs_code[:insert_at] + line + cs_code[insert_at:]

    @staticmethod
    def _status_for_mod_sources_root(status_dict: dict) -> dict:
        """Map Gatekeeper status to the same keys the TUI expects at ModSources root."""
        raw = status_dict.get("status", "building")
        msg = (status_dict.get("message") or "").strip()
        if raw == "finishing":
            return {
                "status": "building",
                "stage_label": msg or "Gatekeeper — Finalizing...",
                "stage_pct": 95,
            }
        if raw == "error":
            err = msg or "Build failed."
            code = status_dict.get("error_code")
            if code:
                err = f"{err} ({code})"
            return {
                "status": "error",
                "error_code": status_dict.get("error_code", "BUILD_FAIL"),
                "message": err,
                "stage_label": msg or err,
                "stage_pct": 80,
            }
        if raw == "building":
            return {
                "status": "building",
                "stage_label": msg or "Gatekeeper — Compiling...",
                "stage_pct": 85,
            }
        return {
            "status": "building",
            "stage_label": msg or "Gatekeeper — Compiling...",
            "stage_pct": 85,
        }

    def _write_status(self, status_dict: dict) -> None:
        """Write generation_status.json under the mod folder and mirror to ModSources root for the TUI."""
        self._mod_root.mkdir(parents=True, exist_ok=True)
        _atomic_write_json(self._mod_root / "generation_status.json", status_dict)

        root_payload = self._status_for_mod_sources_root(status_dict)
        _atomic_write_json(
            self._mod_root.parent / "generation_status.json", root_payload
        )

    def _stage_files(
        self,
        cs_code: str,
        hjson_code: str,
        item_name: str,
        sprite_path: str | None,
        projectile_sprite_path: str | None = None,
        manifest: dict | None = None,
    ) -> None:
        """Write code and sprites to the ModSources paths tModLoader autoloads."""
        item_sprite: Path | None = None
        projectile_sprite: Path | None = None

        if not sprite_path and not self._uses_vanilla_texture(cs_code, item_name):
            raise ValueError(
                f"item sprite path is required for generated item {item_name!r}"
            )

        if sprite_path:
            item_sprite = Path(sprite_path)
            if not item_sprite.exists():
                raise FileNotFoundError(
                    f"item sprite path does not exist: {item_sprite}"
                )
            if item_sprite.stem != item_name:
                raise ValueError(
                    "item sprite name mismatch: "
                    f"asset {item_sprite.stem!r} does not match item_name {item_name!r}"
                )

        hjson_effective = self._resolve_staging_hjson(
            hjson_code, manifest, item_name, self._mod_root.name
        )

        projectile_name = self._extract_projectile_name(cs_code)
        if (
            projectile_name
            and not projectile_sprite_path
            and not self._uses_vanilla_texture(cs_code, projectile_name)
        ):
            raise ValueError(
                "projectile sprite path is required for generated projectile "
                f"{projectile_name!r}"
            )

        if projectile_sprite_path:
            projectile_sprite = Path(projectile_sprite_path)
            if not projectile_sprite.exists():
                raise FileNotFoundError(
                    f"projectile sprite path does not exist: {projectile_sprite}"
                )
            if not projectile_name:
                raise ValueError(
                    "projectile sprite provided, but codegen emitted no ModProjectile class"
                )
            source_name = projectile_sprite.stem
            if source_name != projectile_name:
                raise ValueError(
                    "projectile sprite name mismatch: "
                    f"asset {source_name!r} does not match ModProjectile {projectile_name!r}"
                )

        cs_prepared = self._inject_mod_projectile_texture(
            cs_code,
            projectile_name,
            self._mod_root.name,
            use_mod_projectile_png=bool(projectile_sprite and projectile_name),
        )

        self._clear_generated_content_surface()

        items_dir = self._mod_root / "Content" / "Items"
        items_dir.mkdir(parents=True, exist_ok=True)

        (items_dir / f"{item_name}.cs").write_text(cs_prepared, encoding="utf-8")

        if item_sprite:
            shutil.copy2(item_sprite, items_dir / f"{item_name}.png")

        if projectile_sprite and projectile_name:
            projectiles_dir = self._mod_root / "Content" / "Projectiles"
            projectiles_dir.mkdir(parents=True, exist_ok=True)
            shutil.copy2(
                projectile_sprite, projectiles_dir / f"{projectile_name}.png"
            )

        if hjson_effective:
            self._merge_hjson(hjson_effective, item_name)

        self._ensure_build_files()

    def _clear_generated_content_surface(self) -> None:
        """Remove stale generated loadable content before staging the next forge.

        tModLoader compiles every C# file under the ModSources folder. Leaving
        previous generated weapons in place means a stale bad file can break the
        current build, or make live testing exercise the wrong item behavior.
        Build metadata and the mod entry class are intentionally preserved.
        """
        for rel in ("Content", "Localization"):
            path = self._mod_root / rel
            if path.exists():
                shutil.rmtree(path)

    def _ensure_build_files(self) -> None:
        """Create build.txt, description.txt, and Mod entry class if missing."""
        build_txt = self._mod_root / "build.txt"
        desc_txt = self._mod_root / "description.txt"
        if not build_txt.exists():
            build_txt.write_text(_DEFAULT_BUILD_TXT, encoding="utf-8")
        if not desc_txt.exists():
            desc_txt.write_text(_DEFAULT_DESCRIPTION_TXT, encoding="utf-8")
        self._ensure_mod_entry_class()

    def _ensure_mod_entry_class(self) -> None:
        """Write ``<FolderName>.cs`` with ``class FolderName : Mod`` if absent."""
        mod_name = self._mod_root.name
        entry = self._mod_root / f"{mod_name}.cs"
        if entry.exists():
            return
        entry.write_text(
            _DEFAULT_MOD_ENTRY_CS.format(mod_name=mod_name), encoding="utf-8"
        )

    def _merge_hjson(self, hjson_block: str, item_name: str) -> None:
        """Append or replace an item's HJSON block in en-US.hjson."""
        hjson_path = self._mod_root / "Localization" / "en-US.hjson"
        hjson_path.parent.mkdir(parents=True, exist_ok=True)

        if not hjson_path.exists():
            hjson_path.write_text(hjson_block, encoding="utf-8")
            return

        existing = hjson_path.read_text(encoding="utf-8")

        new_block = _extract_item_hjson_block(hjson_block, item_name)
        if not new_block:
            hjson_path.write_text(hjson_block, encoding="utf-8")
            return

        old_sub = _extract_item_hjson_block(existing, item_name)
        if old_sub is not None:
            start = existing.find(old_sub)
            if start >= 0:
                updated = (
                    existing[:start] + new_block + existing[start + len(old_sub) :]
                )
                hjson_path.write_text(updated, encoding="utf-8")
                return

        items_close = re.search(r"(\n\t\t\})", existing)
        if items_close:
            insert_pos = items_close.start()
            updated = (
                existing[:insert_pos] + "\n\t\t\t" + new_block + existing[insert_pos:]
            )
            hjson_path.write_text(updated, encoding="utf-8")
        else:
            hjson_path.write_text(hjson_block, encoding="utf-8")

    def _ensure_mod_enabled(self, mod_name: str) -> None:
        """Ensure mod_name appears in tModLoader's enabled.json."""
        enabled_path = self._mod_root.parent.parent / "Mods" / "enabled.json"
        enabled_path.parent.mkdir(parents=True, exist_ok=True)

        try:
            enabled: list[str] = (
                json.loads(enabled_path.read_text(encoding="utf-8"))
                if enabled_path.exists()
                else []
            )
        except (json.JSONDecodeError, OSError):
            enabled = []

        if mod_name not in enabled:
            enabled.append(mod_name)
            _atomic_write_text(enabled_path, json.dumps(enabled, indent=2) + "\n")

    def _run_tmod_build(self) -> CompileResult:
        """Run the tModLoader headless build as a blocking subprocess.

        macOS SIP strips DYLD_* env vars from child processes, so we use a
        wrapper shell script that sets DYLD_LIBRARY_PATH and ``exec``s dotnet
        in-place — preserving the variable for native library resolution.
        """
        mod_name = self._mod_root.name
        mod_sources_dir = self._mod_root.parent
        tmod_dir = self._tmod_dll.parent
        saved_dir = mod_sources_dir.parent  # e.g. .../tModLoader

        self._remove_empty_tmodloader_shadow_source(tmod_dir / mod_name)

        wrapper = Path(__file__).resolve().parent / "tmod_build.sh"

        cmd = [
            str(wrapper),
            str(tmod_dir),
            "-build",
            str(self._mod_root),
            "-tmlsavedirectory",
            str(saved_dir),
        ]

        proc = subprocess.run(
            cmd,
            capture_output=True,
            text=True,
        )
        output = proc.stdout + proc.stderr
        return CompileResult(success=proc.returncode == 0, output=output)

    @staticmethod
    def _remove_empty_tmodloader_shadow_source(path: Path) -> None:
        """Remove empty install-dir source shadows so ``-build Name`` uses ModSources.

        tModLoader is launched from its install directory for dependency resolution.
        If an empty directory with the mod name exists there, it can be selected as
        the source and produce an empty stub .tmod. Only empty directories are
        removed; non-empty folders are left untouched.
        """
        try:
            if path.is_dir() and not any(path.iterdir()):
                path.rmdir()
        except OSError:
            pass
